apiVersion: skaffold/v2beta17
kind: Config
metadata:
  name: dispatcher-service
build:
  artifacts:
    - image: polarbookshop/dispatcher-service
      buildpacks:
        builder: gcr.io/paketo-buildpacks/builder:base
        env:
          - BP_JVM_VERSION=16.*
deploy:
  helm:
    releases:
      - name: polar-rabbitmq
        remoteChart: bitnami/rabbitmq
        setValues:
          fullnameOverride: polar-rabbitmq
          clustering.enabled: false
          persistence.enabled: false
          auth.username: user
          auth.password: password
  kubectl:
    manifests:
      - k8s/*.yml
