apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      terminationGracePeriodSeconds: 20
      containers:
        - name: catalog-service
          image: polarbookshop/order-service:0.0.1-SNAPSHOT
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 9002
          env:
            - name: SPRING_DATASOURCE_URL
              value: r2dbc:postgresql://polar-postgres-order:5432/polardb_order
