apiVersion: skaffold/v2beta17
kind: Config
metadata:
  name: edge-service
build:
  artifacts:
    - image: polarbookshop/edge-service
      buildpacks:
        builder: gcr.io/paketo-buildpacks/builder:base
        env:
          - BP_JVM_VERSION=16.*
deploy:
  helm:
    releases:
      - name: polar-redis
        remoteChart: bitnami/redis
        setValues:
          architecture: standalone
          fullnameOverride: polar-redis
          master.persistence.enabled: false
          auth.password: admin
  kubectl:
    manifests:
      - k8s/*.yml
