spring:
  config:
    import: optional:configserver:,configtree:/workspace/secrets/*/
  cloud:
    bus:
      enabled: true
    config:
      uri: http://config-service
  datasource:
    url: jdbc:postgresql://polar-postgres-catalog/polardb_catalog
  rabbitmq:
    host: polar-rabbitmq