spring:
  config:
    import: optional:configserver:,configtree:/workspace/secrets/*/
  cloud:
    config:
      uri: http://config-service
  rabbitmq:
    host: polar-rabbitmq.polar-rabbitmq.svc.cluster.local
  zipkin:
    enabled: false
  redis:
    host: polar-redis