apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-service
  template:
    spec:
      terminationGracePeriodSeconds: 20
      containers:
        - name: config-service
          image: polarbookshop/config-service:0.0.1-SNAPSHOT
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 8888
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "25"
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: polar-rabbitmq
                  key: rabbitmq-password
          volumeMounts:
            - name: config-service-volume
              mountPath: /workspace/config
            - name: config-service-volume-secret
              mountPath: /workspace/secrets/config-service
      volumes:
        - name: config-service-volume
          configMap:
            name: config-service
        - name: config-service-volume-secret
          secret:
            secretName: config-service
